In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np

# Array Creation

In [3]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array((1,2,3,4,5))
a2

array([1, 2, 3, 4, 5])

In [6]:
a3 = np.array({3,3,3,3,6,5,4,5,6,4,4})
a3

array({3, 4, 5, 6}, dtype=object)

In [7]:
a4 = np.array({'a':1, 'b':2, 'c':3})
a4

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [8]:
a5 = np.array([[1, 2, 3], [4, 5, 6]])
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a6 = np.array([(1, 2, 3), (4, 5, 6)])
a6

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a = np.array([[9, 8, 2, 7], [1, 2, 8, 9], [6, 5, 4 ,2]])
a

array([[9, 8, 2, 7],
       [1, 2, 8, 9],
       [6, 5, 4, 2]])

In [11]:
a.shape #Returns the shape of an array

(3, 4)

In [12]:
a.size #Returns the number of elements in an array

12

In [13]:
a.ndim #Returns the number of dimensions of an array

2

In [14]:
np.arange(1,11,2) #Returns a 1-D array of given range

array([1, 3, 5, 7, 9])

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.zeros((4,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.ones((4,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.full((4,5), 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [22]:
np.full((4,4), 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [23]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [25]:
np.linspace(9,10,7)

array([ 9.        ,  9.16666667,  9.33333333,  9.5       ,  9.66666667,
        9.83333333, 10.        ])

In [26]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Random Functions

In [29]:
np.random.rand(4) # Returns random float numbers between 0 and 1 (exclusive)

array([0.04662333, 0.8982509 , 0.0761095 , 0.51175614])

In [30]:
np.random.rand(3,4)

array([[0.31324613, 0.22811453, 0.49929297, 0.77388104],
       [0.29057654, 0.41188738, 0.73739436, 0.01462674],
       [0.94815803, 0.55521327, 0.41338954, 0.48433299]])

In [31]:
np.random.rand(3,4)*100

array([[70.60306302, 25.31939012, 93.64524099, 57.87117419],
       [75.46689477, 97.02179613, 46.4845551 ,  9.10209681],
       [90.14193563, 94.46089397, 91.33288835, 23.64024245]])

In [32]:
np.random.randint(1,10,(3,3)) #Returns random integers between given start (inclusive) and stop (exclusive)

array([[1, 3, 7],
       [8, 4, 8],
       [6, 1, 1]])

In [33]:
np.random.randint(10,100,(3,4))

array([[86, 52, 45, 14],
       [85, 45, 83, 80],
       [39, 63, 96, 17]])

# Mathematical Functions

In [34]:
a = np.array([4,5,6,7])
a

array([4, 5, 6, 7])

In [35]:
b = np.array([5,7,2,3])
b

array([5, 7, 2, 3])

In [36]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
d = np.array([[3,4,2], [6,2,5], [1,6,8]])
d

array([[3, 4, 2],
       [6, 2, 5],
       [1, 6, 8]])

In [38]:
np.add(a,b)

array([ 9, 12,  8, 10])

In [39]:
np.add(c,d)

array([[ 4,  6,  5],
       [10,  7, 11],
       [ 8, 14, 17]])

In [40]:
np.subtract(a,b)

array([-1, -2,  4,  4])

In [41]:
np.subtract(c,d)

array([[-2, -2,  1],
       [-2,  3,  1],
       [ 6,  2,  1]])

In [42]:
np.multiply(a,b)

array([20, 35, 12, 21])

In [43]:
np.multiply(c,d)

array([[ 3,  8,  6],
       [24, 10, 30],
       [ 7, 48, 72]])

In [44]:
np.divide(a,b)

array([0.8       , 0.71428571, 3.        , 2.33333333])

In [45]:
np.divide(c,d)

array([[0.33333333, 0.5       , 1.5       ],
       [0.66666667, 2.5       , 1.2       ],
       [7.        , 1.33333333, 1.125     ]])

In [46]:
np.power(a,b)

array([ 1024, 78125,    36,   343])

In [47]:
np.power(c,d)

array([[       1,       16,        9],
       [    4096,       25,     7776],
       [       7,   262144, 43046721]])

In [48]:
np.mod(a,b)

array([4, 5, 0, 1])

In [49]:
np.mod(c,d)

array([[1, 2, 1],
       [4, 1, 1],
       [0, 2, 1]])

In [50]:
a1 = np.array([-2,-3,1,5])
a1

array([-2, -3,  1,  5])

In [51]:
np.abs(a1) #Returns positive equivalent of the values

array([2, 3, 1, 5])

In [52]:
np.sin(a1)

array([-0.90929743, -0.14112001,  0.84147098, -0.95892427])

In [53]:
np.cos(a1)

array([-0.41614684, -0.9899925 ,  0.54030231,  0.28366219])

In [54]:
np.tan(a1)

array([ 2.18503986,  0.14254654,  1.55740772, -3.38051501])

In [55]:
np.exp(a1) #Returns exponential values

array([1.35335283e-01, 4.97870684e-02, 2.71828183e+00, 1.48413159e+02])

In [56]:
np.log(a1)

array([       nan,        nan, 0.        , 1.60943791])

# Statistical Functions

In [57]:
a1 = np.array([5, 6, 8, 15])
a1

array([ 5,  6,  8, 15])

In [58]:
np.min(a1)

5

In [59]:
np.max(a1)

15

In [60]:
np.mean(a1)

8.5

In [61]:
np.median(a1)

7.0

In [62]:
np.var(a1) #Returns Variance

15.25

In [63]:
np.std(a1) #Returns Standard Deviation # std = var**0.5

3.905124837953327