In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np

# Statistical Functions

+ Row-Wise : 1
+ Column-Wise : 0

In [3]:
a1 = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
a1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
np.min(a1)

2

In [5]:
np.min(a1, 1)

array([2, 5, 8])

In [6]:
np.min(a1, 0)

array([2, 3, 4])

In [7]:
np.max(a1)

10

In [8]:
np.max(a1, 1)

array([ 4,  7, 10])

In [9]:
np.max(a1, 0)

array([ 8,  9, 10])

In [10]:
np.mean(a1)

6.0

In [11]:
np.mean(a1, 1)

array([3., 6., 9.])

In [12]:
np.mean(a1, 0)

array([5., 6., 7.])

In [13]:
np.median(a1)

6.0

In [14]:
np.median(a1, 1)

array([3., 6., 9.])

In [15]:
np.median(a1, 0)

array([5., 6., 7.])

In [16]:
np.var(a1)

6.666666666666667

In [17]:
np.var(a1, 1)

array([0.66666667, 0.66666667, 0.66666667])

In [18]:
np.var(a1, 0)

array([6., 6., 6.])

In [19]:
np.std(a1)

2.581988897471611

In [20]:
np.std(a1, 1)

array([0.81649658, 0.81649658, 0.81649658])

In [21]:
np.std(a1, 0)

array([2.44948974, 2.44948974, 2.44948974])

# Scalar Mathematical Functions

In [22]:
a2 = np.array([4, 3, 6, 7])
a2

array([4, 3, 6, 7])

In [23]:
np.add(a2, 2)

array([6, 5, 8, 9])

In [24]:
np.subtract(a2, 2)

array([2, 1, 4, 5])

In [25]:
np.multiply(a2, 2)

array([ 8,  6, 12, 14])

In [26]:
np.divide(a2, 2)

array([2. , 1.5, 3. , 3.5])

In [27]:
np.mod(a2, 2)

array([0, 1, 0, 1], dtype=int32)

In [28]:
np.power(a2, 2)

array([16,  9, 36, 49], dtype=int32)

# Matrix Functions

In [29]:
a = np.array([[0, 1], [2, 3]])
a

array([[0, 1],
       [2, 3]])

In [30]:
b = np.array([[3, 2], [0, 1]])
b

array([[3, 2],
       [0, 1]])

In [31]:
np.dot(a,b)

array([[0, 1],
       [6, 7]])

In [32]:
np.transpose(a)

array([[0, 2],
       [1, 3]])

In [33]:
np.transpose(b)

array([[3, 0],
       [2, 1]])

In [34]:
m1 = np.array([[2, 3, 4], [5, 6, 7], [1, 2, 8]])
m1

array([[2, 3, 4],
       [5, 6, 7],
       [1, 2, 8]])

In [35]:
np.linalg.inv(m1)

array([[-2.26666667,  1.06666667,  0.2       ],
       [ 2.2       , -0.8       , -0.4       ],
       [-0.26666667,  0.06666667,  0.2       ]])

In [36]:
np.linalg.det(m1)

-14.999999999999993

# Array Manipulation Commands

In [37]:
a2 = np.array([0,1,1,1,3,3,5,5,5])
a2

array([0, 1, 1, 1, 3, 3, 5, 5, 5])

In [38]:
np.unique(a2) #Returns the unique elements of an array

array([0, 1, 3, 5])

In [39]:
a3 = np.array([1, 2, 3, 4])
a3

array([1, 2, 3, 4])

In [40]:
np.repeat(a3, 4) #Returns an array of repeated elements according to given input

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [41]:
np.unique(np.repeat(a3, 4))

array([1, 2, 3, 4])

In [42]:
np.where(a3 == 2) #Returns the index of the given value in an array

(array([1], dtype=int64),)

In [43]:
ma = np.random.randint(0, 100, (2, 4))
ma

array([[80, 18, 91, 14],
       [98, 41, 77, 61]])

In [44]:
mb = np.random.randint(0, 100, (4, 4))
mb

array([[20, 74, 98, 69],
       [ 0, 50, 31, 49],
       [84, 81, 48,  6],
       [11, 24, 89,  1]])

In [45]:
np.concatenate((ma,mb))

array([[80, 18, 91, 14],
       [98, 41, 77, 61],
       [20, 74, 98, 69],
       [ 0, 50, 31, 49],
       [84, 81, 48,  6],
       [11, 24, 89,  1]])

In [46]:
mc = np.random.randint(0, 50, (4, 4))
mc

array([[43,  9, 17, 26],
       [38, 34, 19,  6],
       [10,  4, 27, 19],
       [22, 44, 19, 24]])

In [47]:
md = np.random.randint(10, 60, (4, 4))
md

array([[19, 34, 49, 24],
       [23, 44, 10, 17],
       [48, 29, 45, 59],
       [38, 47, 51, 50]])

In [48]:
np.concatenate((mc,md), 1)

array([[43,  9, 17, 26, 19, 34, 49, 24],
       [38, 34, 19,  6, 23, 44, 10, 17],
       [10,  4, 27, 19, 48, 29, 45, 59],
       [22, 44, 19, 24, 38, 47, 51, 50]])

In [49]:
np.concatenate((mc,md), 0)

array([[43,  9, 17, 26],
       [38, 34, 19,  6],
       [10,  4, 27, 19],
       [22, 44, 19, 24],
       [19, 34, 49, 24],
       [23, 44, 10, 17],
       [48, 29, 45, 59],
       [38, 47, 51, 50]])

In [50]:
me = np.array([[1, 2, 3], [4, 5, 6]])
me

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.append(me, [7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.append(me, [[7, 8, 9]], 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.append(me, [[7, 8], [9, 10]], 1)

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

In [54]:
mf = np.array([[1, 2], [3, 4], [5, 6]])
mf

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
np.insert(mf, 1, [11])

array([ 1, 11,  2,  3,  4,  5,  6])

In [56]:
np.insert(mf, 1, [[11, 12]], 0)

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [57]:
np.insert(mf, 1, [[11, 12, 13]], 1)

array([[ 1, 11,  2],
       [ 3, 12,  4],
       [ 5, 13,  6]])

In [58]:
mg = np.arange(16).reshape(4,4)
mg

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.split(mg, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [60]:
np.split(mg, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [61]:
np.split(mg, 2, 0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [62]:
np.split(mg, 2, 1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [63]:
np.hsplit(mg, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [64]:
np.hsplit(mg, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [65]:
np.vsplit(mg, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [66]:
np.vsplit(mg, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [67]:
mi = np.array([[1, 2], [3, 4]])
mi

array([[1, 2],
       [3, 4]])

In [68]:
mj = np.array([[5, 6], [7, 8]])
mj

array([[5, 6],
       [7, 8]])

In [69]:
ax = np.array([1,2,3,4])
ax

array([1, 2, 3, 4])

In [70]:
ay = np.array([5,6,7,8])
ay

array([5, 6, 7, 8])

In [71]:
np.stack((ax,ay))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
np.stack((ax,ay))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
np.stack((mi,mj))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [74]:
np.stack((mi,mj), 0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [75]:
np.stack((mi,mj), 1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [76]:
np.concatenate((mi,mj))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [77]:
mk = np.arange(12).reshape(3,4)
mk

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
np.delete(mk, 5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [79]:
np.delete(mk, (0), 0) # Here axis = 0 for row

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
np.delete(mk, (0), 1) # Here axis = 1 for column

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

# Array Indexing and Slicing

In [81]:
a3 = np.array([1, 2, 3, 4])
a3

array([1, 2, 3, 4])

In [82]:
a3[0]

1

In [83]:
a3[1:3]

array([2, 3])

In [84]:
m2 = np.array([[2, 3, 4], [8, 4, 5], [6, 2, 4]])
m2

array([[2, 3, 4],
       [8, 4, 5],
       [6, 2, 4]])

In 2-dimensional array, the **indexing** goes by first **ROW** and then **COLUMN** => [< row >, < column >]

In [85]:
m2[0,0]

2

In [86]:
m2[2,2]

4

In [87]:
m2[2,0]

6

In [88]:
np.where(m2 == 8)

(array([1], dtype=int64), array([0], dtype=int64))

In [89]:
m3 = np.array([[2, 5, 6, 8], [1, 2, 3, 9], [7, 8, 4, 5], [6, 6, 2, 3]])
m3

array([[2, 5, 6, 8],
       [1, 2, 3, 9],
       [7, 8, 4, 5],
       [6, 6, 2, 3]])

In 2-dimensional array, the **sliciing** goes by first **ROW SLICING** and then **COLUMN SLICING** => [< row_slice >, < column_slice >]

In [90]:
m3[1:3,1:3]

array([[2, 3],
       [8, 4]])

In [91]:
m3[0:2,1:3]

array([[5, 6],
       [2, 3]])

In [92]:
m3[:2,1:3]

array([[5, 6],
       [2, 3]])

In [93]:
m3[1:3,1:5]

array([[2, 3, 9],
       [8, 4, 5]])

In [94]:
m3[1:3,1:]

array([[2, 3, 9],
       [8, 4, 5]])

In [95]:
m4 = np.array([[90, 22, 30, 75, 69],
               [66, 28, 2, 3, 99],
               [34, 65, 43, 9, 81],
               [18, 82, 61, 70, 20],
               [93, 8, 77, 81, 72]])
m4

array([[90, 22, 30, 75, 69],
       [66, 28,  2,  3, 99],
       [34, 65, 43,  9, 81],
       [18, 82, 61, 70, 20],
       [93,  8, 77, 81, 72]])

In [96]:
m4[1:3,2:]

array([[ 2,  3, 99],
       [43,  9, 81]])

In [97]:
m4[1:3,:]

array([[66, 28,  2,  3, 99],
       [34, 65, 43,  9, 81]])

In [98]:
m4[1:4:2,1:4:2]

array([[28,  3],
       [82, 70]])

In [99]:
m4[:,:]

array([[90, 22, 30, 75, 69],
       [66, 28,  2,  3, 99],
       [34, 65, 43,  9, 81],
       [18, 82, 61, 70, 20],
       [93,  8, 77, 81, 72]])